CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MARCA(
idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(30) NOT NULL
);
GO

CREATE TABLE CLIENTE(
idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeCliente VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MODELO(
idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(15) NOT NULL
);
GO

CREATE TABLE VEICULO(
idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
placa CHAR(8) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
dataAluguel DATE NOT NULL
);
GO
ALTER TABLE ALUGUEL
ADD dataDevolucao SMALLDATETIME

ALTER TABLE CLIENTE
ADD sobrenomeCliente VARCHAR(30) NOT NULL

SELECT idVeiculo, idModelo, idEmpresa, placa FROM VEICULO

DELETE FROM ALUGUEL WHERE idVeiculo = 1

SELECT  idAluguel, ISNULL(CLIENTE.idCliente,0)AS idCliente, nomeCliente AS CLIENTE, ISNULL(VEICULO.idVeiculo,0)AS idVeiculo , ISNULL(ALUGUEL.dataAluguel, null) AS DataRetirada, ISNULL(ALUGUEL.dataDevolucao, null) AS DataDevolução FROM ALUGUEL RIGHT JOIN CLIENTE ON CLIENTE.idCliente = ALUGUEL.idCliente RIGHT JOIN VEICULO ON ALUGUEL.idVeiculo = VEICULO.idVeiculo

SELECT ISNULL(ALUGUEL.idAluguel,0) AS idAluguel, ISNULL(CLIENTE.idCliente,0)AS idCliente, ISNULL(VEICULO.idVeiculo,0)AS idVeiculo , dataAluguel, dataDevolucao FROM ALUGUEL INNER JOIN CLIENTE ON CLIENTE.idCliente = ALUGUEL.idCliente INNER JOIN VEICULO ON ALUGUEL.idVeiculo = VEICULO.idVeiculo

